drop_anchor:
  description: "Sets the anchor position and optional radius."
  fields:
    radius:
      description: "Anchor Zone Radius in meters. If not specified, a default value will be used."
      example: 30
      required: false

lift_anchor:
  description: "Lifts the anchor, which deletes the Anchor Zone."
  fields: {}

update_anchor_zone:
  description: "Updates the anchor zone radius."
  fields:
    radius:
      description: "Anchor Zone Radius in meters."
      example: 30
      required: true
