# services.yaml
set_anchor:
  description: Set the anchor position and optional radius.
  fields:
    radius:
      description: The radius in meters around the anchor within which movements are allowed. If not specified, the default or previously set value will be used.
      example: 40
      required: false

lift_anchor:
  description: Lift the anchor, deletes Anchor Zone. no parameters needed.
